"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Terminal } from "lucide-react"
import { db } from "@/lib/firebase"
import { collection, writeBatch, doc, getDocs, query, serverTimestamp } from "firebase/firestore"
import { toast } from "sonner"

// Updated Categories based on actual menu
const sampleCategories = [
  {
    id: "cat_chicken_only",
    name: "Chicken Only",
    description: "Fresh fried chicken pieces - no sides, just pure chicken goodness.",
    order: 1,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_tenders",
    name: "Tenders",
    description: "Crispy chicken tenders - perfect for dipping.",
    order: 2,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_wings_more",
    name: "Wings & More Chicken",
    description: "Chicken wings and specialty chicken combinations.",
    order: 3,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_popcorn_nuggets",
    name: "Popcorn Chicken & Nuggets",
    description: "Bite-sized chicken pieces and nuggets.",
    order: 4,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_single_meals",
    name: "Single Meals",
    description: "Complete meals with chicken, sides, and drink.",
    order: 5,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_family_meals",
    name: "Family Meals",
    description: "Large portions perfect for sharing with family.",
    order: 6,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_twisters",
    name: "Twisters",
    description: "Delicious chicken wraps with various flavors.",
    order: 7,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_sandwiches_burgers",
    name: "Sandwiches & Burgers",
    description: "Crispy chicken sandwiches and burgers.",
    order: 8,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_sides_dessert",
    name: "Sides & Dessert",
    description: "Perfect sides and sweet treats to complete your meal.",
    order: 9,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_kids_meals",
    name: "Kids Meals",
    description: "Kid-friendly portions with a drink and side.",
    order: 10,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_sauces",
    name: "Dipping Sauces",
    description: "Delicious sauces to enhance your meal.",
    order: 11,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "cat_drinks",
    name: "Drinks",
    description: "Refreshing beverages to complement your meal.",
    order: 12,
    isActive: true,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
]

// Updated Menu Items based on actual menu
const sampleMenuItems = [
  // Chicken Only
  {
    id: "item_single_piece",
    name: "Single Piece Chicken",
    description: "One piece of our signature crispy fried chicken.",
    price: 2.99,
    category: "Chicken Only",
    categoryId: "cat_chicken_only",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["single", "classic"],
    variations: [],
    addOns: [],
    nutrition: { calories: "250kcal", protein: "18g", allergens: ["gluten", "soy"] },
    preparationTime: 5,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_2pc_chicken_only",
    name: "2pc Chicken ONLY",
    description: "Two pieces of our signature crispy fried chicken.",
    price: 8.99,
    category: "Chicken Only",
    categoryId: "cat_chicken_only",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ["popular", "classic"],
    variations: [],
    addOns: [],
    nutrition: { calories: "500kcal", protein: "36g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_3pc_chicken",
    name: "3pc Chicken",
    description: "Three pieces of our signature crispy fried chicken.",
    price: 11.99,
    category: "Chicken Only",
    categoryId: "cat_chicken_only",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["classic"],
    variations: [],
    addOns: [],
    nutrition: { calories: "750kcal", protein: "54g", allergens: ["gluten", "soy"] },
    preparationTime: 10,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_4pc_chicken",
    name: "4pc Chicken",
    description: "Four pieces of our signature crispy fried chicken.",
    price: 14.99,
    category: "Chicken Only",
    categoryId: "cat_chicken_only",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["classic"],
    variations: [],
    addOns: [],
    nutrition: { calories: "1000kcal", protein: "72g", allergens: ["gluten", "soy"] },
    preparationTime: 12,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_6pc_chicken",
    name: "6pc Chicken",
    description: "Six pieces of our signature crispy fried chicken.",
    price: 20.99,
    category: "Chicken Only",
    categoryId: "cat_chicken_only",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["sharing"],
    variations: [],
    addOns: [],
    nutrition: { calories: "1500kcal", protein: "108g", allergens: ["gluten", "soy"] },
    preparationTime: 15,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_9pc_chicken",
    name: "9pc Chicken",
    description: "Nine pieces of our signature crispy fried chicken.",
    price: 32.49,
    category: "Chicken Only",
    categoryId: "cat_chicken_only",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["sharing", "family"],
    variations: [],
    addOns: [],
    nutrition: { calories: "2250kcal", protein: "162g", allergens: ["gluten", "soy"] },
    preparationTime: 18,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_12pc_chicken",
    name: "12pc Chicken",
    description: "Twelve pieces of our signature crispy fried chicken.",
    price: 36.99,
    category: "Chicken Only",
    categoryId: "cat_chicken_only",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ["family", "party"],
    variations: [],
    addOns: [],
    nutrition: { calories: "3000kcal", protein: "216g", allergens: ["gluten", "soy"] },
    preparationTime: 20,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Tenders
  {
    id: "item_single_tender",
    name: "Single Tender",
    description: "One crispy chicken tender, perfect for a quick bite.",
    price: 2.25,
    category: "Tenders",
    categoryId: "cat_tenders",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["single", "tender"],
    variations: [],
    addOns: [],
    nutrition: { calories: "180kcal", protein: "15g", allergens: ["gluten", "soy"] },
    preparationTime: 5,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_3pc_tenders",
    name: "3 pcs Tenders",
    description: "Three crispy chicken tenders.",
    price: 7.99,
    category: "Tenders",
    categoryId: "cat_tenders",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 0,
    tags: ["popular", "tender"],
    variations: [],
    addOns: [],
    nutrition: { calories: "540kcal", protein: "45g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_6pc_tenders",
    name: "6 pcs Tenders",
    description: "Six crispy chicken tenders.",
    price: 14.99,
    category: "Tenders",
    categoryId: "cat_tenders",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["sharing", "tender"],
    variations: [],
    addOns: [],
    nutrition: { calories: "1080kcal", protein: "90g", allergens: ["gluten", "soy"] },
    preparationTime: 12,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_tenders_snack",
    name: "Tenders Snack",
    description: "Perfect snack-sized portion of chicken tenders.",
    price: 6.99,
    category: "Tenders",
    categoryId: "cat_tenders",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["snack", "tender"],
    variations: [],
    addOns: [],
    nutrition: { calories: "420kcal", protein: "35g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_3pc_tenders_meal",
    name: "3 pc Tenders Meal",
    description: "Three chicken tenders with side and drink.",
    price: 9.99,
    category: "Tenders",
    categoryId: "cat_tenders",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 0,
    tags: ["meal", "tender", "value"],
    variations: [],
    addOns: [],
    nutrition: { calories: "720kcal", protein: "50g", allergens: ["gluten", "soy"] },
    preparationTime: 10,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_6pc_tenders_meal",
    name: "6 pc Tenders Meal",
    description: "Six chicken tenders with side and drink.",
    price: 16.99,
    category: "Tenders",
    categoryId: "cat_tenders",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["meal", "tender", "sharing"],
    variations: [],
    addOns: [],
    nutrition: { calories: "1260kcal", protein: "95g", allergens: ["gluten", "soy"] },
    preparationTime: 15,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Wings & More Chicken
  {
    id: "item_10pc_wings",
    name: "10pcs Chicken Wings",
    description: "Ten crispy chicken wings with your choice of sauce.",
    price: 9.99,
    category: "Wings & More Chicken",
    categoryId: "cat_wings_more",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 2,
    tags: ["wings", "popular"],
    variations: [],
    addOns: [],
    nutrition: { calories: "800kcal", protein: "60g", allergens: ["gluten"] },
    preparationTime: 15,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_tenders_popcorn_combo",
    name: "10 Tenders & 40 Popcorn Chicken",
    description: "Ultimate chicken combo with tenders and popcorn chicken.",
    price: 34.99,
    category: "Wings & More Chicken",
    categoryId: "cat_wings_more",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["combo", "sharing", "variety"],
    variations: [],
    addOns: [],
    nutrition: { calories: "2400kcal", protein: "180g", allergens: ["gluten", "soy"] },
    preparationTime: 20,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_tenders_chicken_combo",
    name: "6 Tenders & 6pc Chicken",
    description: "Perfect combination of tenders and chicken pieces.",
    price: 45.99,
    category: "Wings & More Chicken",
    categoryId: "cat_wings_more",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["combo", "premium", "variety"],
    variations: [],
    addOns: [],
    nutrition: { calories: "2580kcal", protein: "198g", allergens: ["gluten", "soy"] },
    preparationTime: 25,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Popcorn Chicken & Nuggets
  {
    id: "item_popcorn_10pc",
    name: "Popcorn Chicken (10 pcs)",
    description: "Ten bite-sized pieces of crispy popcorn chicken.",
    price: 3.99,
    category: "Popcorn Chicken & Nuggets",
    categoryId: "cat_popcorn_nuggets",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["snack", "bite-sized"],
    variations: [],
    addOns: [],
    nutrition: { calories: "320kcal", protein: "24g", allergens: ["gluten", "soy"] },
    preparationTime: 5,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_popcorn_20pc",
    name: "Popcorn Chicken (20 pcs)",
    description: "Twenty bite-sized pieces of crispy popcorn chicken.",
    price: 6.99,
    category: "Popcorn Chicken & Nuggets",
    categoryId: "cat_popcorn_nuggets",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 0,
    tags: ["snack", "bite-sized", "sharing"],
    variations: [],
    addOns: [],
    nutrition: { calories: "640kcal", protein: "48g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_nuggets_6pc",
    name: "Chicken Nuggets (6 pcs)",
    description: "Six golden chicken nuggets.",
    price: 4.25,
    category: "Popcorn Chicken & Nuggets",
    categoryId: "cat_popcorn_nuggets",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["nuggets", "classic"],
    variations: [],
    addOns: [],
    nutrition: { calories: "380kcal", protein: "30g", allergens: ["gluten", "soy"] },
    preparationTime: 6,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_nuggets_12pc",
    name: "Chicken Nuggets (12 pcs)",
    description: "Twelve golden chicken nuggets.",
    price: 7.99,
    category: "Popcorn Chicken & Nuggets",
    categoryId: "cat_popcorn_nuggets",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["nuggets", "sharing"],
    variations: [],
    addOns: [],
    nutrition: { calories: "760kcal", protein: "60g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Single Meals
  {
    id: "item_tender_snack_meal",
    name: "Tender Snack",
    description: "Tender snack with side and drink.",
    price: 6.99,
    category: "Single Meals",
    categoryId: "cat_single_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["meal", "snack", "value"],
    variations: [],
    addOns: [],
    nutrition: { calories: "600kcal", protein: "40g", allergens: ["gluten", "soy"] },
    preparationTime: 10,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_2pc_single_meal",
    name: "2pc Single Meal",
    description: "Two pieces of chicken with side and drink.",
    price: 9.99,
    category: "Single Meals",
    categoryId: "cat_single_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ["meal", "popular", "value"],
    variations: [],
    addOns: [],
    nutrition: { calories: "680kcal", protein: "41g", allergens: ["gluten", "soy"] },
    preparationTime: 12,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_3pc_single_meal",
    name: "3pc Single Meal",
    description: "Three pieces of chicken with side and drink.",
    price: 13.99,
    category: "Single Meals",
    categoryId: "cat_single_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["meal"],
    variations: [],
    addOns: [],
    nutrition: { calories: "930kcal", protein: "59g", allergens: ["gluten", "soy"] },
    preparationTime: 15,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_4pc_single_meal",
    name: "4pc Single Meal",
    description: "Four pieces of chicken with side and drink.",
    price: 17.99,
    category: "Single Meals",
    categoryId: "cat_single_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["meal", "hearty"],
    variations: [],
    addOns: [],
    nutrition: { calories: "1180kcal", protein: "77g", allergens: ["gluten", "soy"] },
    preparationTime: 18,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_6pc_single_meal",
    name: "6pc Single Meal",
    description: "Six pieces of chicken with side and drink.",
    price: 28.99,
    category: "Single Meals",
    categoryId: "cat_single_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["meal", "sharing"],
    variations: [],
    addOns: [],
    nutrition: { calories: "1680kcal", protein: "113g", allergens: ["gluten", "soy"] },
    preparationTime: 20,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Family Meals
  {
    id: "item_anytime_10",
    name: "Anytime 10",
    description: "Ten pieces of chicken perfect for any time.",
    price: 34.99,
    category: "Family Meals",
    categoryId: "cat_family_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ["family", "value", "popular"],
    variations: [],
    addOns: [],
    nutrition: { calories: "2500kcal", protein: "180g", allergens: ["gluten", "soy"] },
    preparationTime: 25,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_9pc_family_meal",
    name: "9pc Family Meal",
    description: "Nine pieces of chicken with family sides.",
    price: 39.99,
    category: "Family Meals",
    categoryId: "cat_family_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["family", "complete"],
    variations: [],
    addOns: [],
    nutrition: { calories: "2700kcal", protein: "167g", allergens: ["gluten", "soy"] },
    preparationTime: 25,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_12pc_family_meal",
    name: "12pc Family Meal",
    description: "Twelve pieces of chicken with family sides.",
    price: 49.99,
    category: "Family Meals",
    categoryId: "cat_family_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ["family", "party", "premium"],
    variations: [],
    addOns: [],
    nutrition: { calories: "3600kcal", protein: "221g", allergens: ["gluten", "soy"] },
    preparationTime: 30,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Twisters
  {
    id: "item_zmax_twister",
    name: "Z-max Chicken Twister",
    description: "Our signature spicy chicken wrap with premium ingredients.",
    price: 9.99,
    category: "Twisters",
    categoryId: "cat_twisters",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 3,
    tags: ["signature", "spicy", "wrap"],
    variations: [],
    addOns: [],
    nutrition: { calories: "620kcal", protein: "35g", allergens: ["gluten", "dairy", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_chicken_twister",
    name: "Chicken Twister",
    description: "Classic chicken wrap with fresh vegetables and sauce.",
    price: 9.99,
    category: "Twisters",
    categoryId: "cat_twisters",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["classic", "wrap"],
    variations: [],
    addOns: [],
    nutrition: { calories: "580kcal", protein: "32g", allergens: ["gluten", "dairy", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_butter_chicken_twister",
    name: "Butter Chicken Twister",
    description: "Creamy butter chicken wrapped in a soft tortilla.",
    price: 9.99,
    category: "Twisters",
    categoryId: "cat_twisters",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["creamy", "butter", "wrap"],
    variations: [],
    addOns: [],
    nutrition: { calories: "640kcal", protein: "34g", allergens: ["gluten", "dairy", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_twister_combo",
    name: "Twister Combo",
    description: "Any twister with side and drink.",
    price: 12.99,
    category: "Twisters",
    categoryId: "cat_twisters",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ["combo", "value", "meal"],
    variations: [],
    addOns: [],
    nutrition: { calories: "760kcal", protein: "37g", allergens: ["gluten", "dairy", "soy"] },
    preparationTime: 10,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_twisters_meal",
    name: "Twisters Meal",
    description: "Premium twister meal with multiple sides.",
    price: 14.99,
    category: "Twisters",
    categoryId: "cat_twisters",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["premium", "meal"],
    variations: [],
    addOns: [],
    nutrition: { calories: "920kcal", protein: "42g", allergens: ["gluten", "dairy", "soy"] },
    preparationTime: 12,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Sandwiches & Burgers
  {
    id: "item_zmax_sandwich",
    name: "Z-max Chicken Sandwich",
    description: "Our signature spicy chicken sandwich with premium toppings.",
    price: 9.99,
    category: "Sandwiches & Burgers",
    categoryId: "cat_sandwiches_burgers",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 3,
    tags: ["signature", "spicy", "premium"],
    variations: [],
    addOns: [],
    nutrition: { calories: "650kcal", protein: "38g", allergens: ["gluten", "dairy", "soy", "egg"] },
    preparationTime: 10,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_crispy_sandwich",
    name: "Crispy Chicken Sandwich",
    description: "Classic crispy chicken sandwich with lettuce and mayo.",
    price: 9.99,
    category: "Sandwiches & Burgers",
    categoryId: "cat_sandwiches_burgers",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["classic", "crispy"],
    variations: [],
    addOns: [],
    nutrition: { calories: "590kcal", protein: "35g", allergens: ["gluten", "dairy", "soy", "egg"] },
    preparationTime: 10,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_veggie_burger",
    name: "Veggie Burger",
    description: "Plant-based burger with fresh vegetables.",
    price: 9.99,
    category: "Sandwiches & Burgers",
    categoryId: "cat_sandwiches_burgers",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["vegetarian", "healthy"],
    variations: [],
    addOns: [],
    nutrition: { calories: "480kcal", protein: "18g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_zmax_veggie_burger",
    name: "Z-max Veggie Burger",
    description: "Premium plant-based burger with signature spices.",
    price: 9.99,
    category: "Sandwiches & Burgers",
    categoryId: "cat_sandwiches_burgers",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 2,
    tags: ["vegetarian", "signature", "spicy"],
    variations: [],
    addOns: [],
    nutrition: { calories: "520kcal", protein: "20g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_junior_burger",
    name: "Junior Chicken Burger",
    description: "Smaller chicken burger perfect for lighter appetites.",
    price: 7.99,
    category: "Sandwiches & Burgers",
    categoryId: "cat_sandwiches_burgers",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["junior", "smaller"],
    variations: [],
    addOns: [],
    nutrition: { calories: "420kcal", protein: "25g", allergens: ["gluten", "dairy", "soy", "egg"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_sandwich_combo",
    name: "Sandwich Combo",
    description: "Any sandwich with side and drink.",
    price: 12.99,
    category: "Sandwiches & Burgers",
    categoryId: "cat_sandwiches_burgers",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ["combo", "value", "meal"],
    variations: [],
    addOns: [],
    nutrition: { calories: "770kcal", protein: "40g", allergens: ["gluten", "dairy", "soy", "egg"] },
    preparationTime: 12,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_sandwich_meal",
    name: "Sandwich Meal",
    description: "Premium sandwich meal with multiple sides.",
    price: 15.99,
    category: "Sandwiches & Burgers",
    categoryId: "cat_sandwiches_burgers",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["premium", "meal"],
    variations: [],
    addOns: [],
    nutrition: { calories: "930kcal", protein: "45g", allergens: ["gluten", "dairy", "soy", "egg"] },
    preparationTime: 15,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Sides & Dessert
  {
    id: "item_french_fries",
    name: "French Fries",
    description: "Golden crispy french fries.",
    price: 3.49,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 0,
    tags: ["classic", "popular"],
    variations: [
      { name: "Regular", priceModifier: 0 },
      { name: "Large", priceModifier: 1.5 },
      { name: "Family", priceModifier: 4.0 },
    ],
    addOns: [],
    nutrition: { calories: "320kcal", protein: "4g", allergens: ["gluten"] },
    preparationTime: 5,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_curly_fries",
    name: "Curly Fries",
    description: "Seasoned curly fries with special spices.",
    price: 4.99,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["seasoned", "curly"],
    variations: [
      { name: "Regular", priceModifier: 0 },
      { name: "Family", priceModifier: 4.0 },
    ],
    addOns: [],
    nutrition: { calories: "380kcal", protein: "5g", allergens: ["gluten"] },
    preparationTime: 6,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_gravy",
    name: "Gravy",
    description: "Rich and savory chicken gravy.",
    price: 2.49,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["sauce", "savory"],
    variations: [
      { name: "Regular", priceModifier: 0 },
      { name: "Large", priceModifier: 2.0 },
    ],
    addOns: [],
    nutrition: { calories: "80kcal", protein: "2g", allergens: ["gluten"] },
    preparationTime: 1,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_onion_rings",
    name: "Onion Rings",
    description: "Crispy battered onion rings.",
    price: 4.99,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["crispy", "battered"],
    variations: [
      { name: "8 pieces", priceModifier: 0 },
      { name: "16 pieces", priceModifier: 4.0 },
    ],
    addOns: [],
    nutrition: { calories: "380kcal", protein: "5g", allergens: ["gluten"] },
    preparationTime: 5,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_coleslaw",
    name: "Coleslaw Salad",
    description: "Fresh cabbage and carrot salad.",
    price: 2.99,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["fresh", "healthy"],
    variations: [
      { name: "Regular", priceModifier: 0 },
      { name: "Large", priceModifier: 3.0 },
    ],
    addOns: [],
    nutrition: { calories: "180kcal", protein: "2g", allergens: ["egg", "dairy"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_macaroni_salad",
    name: "Macaroni Salad",
    description: "Creamy macaroni salad with vegetables.",
    price: 2.99,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["creamy", "pasta"],
    variations: [
      { name: "Regular", priceModifier: 0 },
      { name: "Large", priceModifier: 3.0 },
    ],
    addOns: [],
    nutrition: { calories: "220kcal", protein: "4g", allergens: ["gluten", "egg", "dairy"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_rice",
    name: "Rice",
    description: "Steamed white rice.",
    price: 2.49,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["simple", "filling"],
    variations: [
      { name: "1 serving", priceModifier: 0 },
      { name: "2 servings", priceModifier: 2.0 },
    ],
    addOns: [],
    nutrition: { calories: "200kcal", protein: "4g", allergens: [] },
    preparationTime: 2,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_garlic_toast",
    name: "Garlic Toast (2 pcs)",
    description: "Two pieces of buttery garlic toast.",
    price: 2.99,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["garlic", "buttery"],
    variations: [],
    addOns: [],
    nutrition: { calories: "240kcal", protein: "6g", allergens: ["gluten", "dairy"] },
    preparationTime: 3,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_dinner_roll",
    name: "Dinner Roll (1 pc)",
    description: "Soft dinner roll.",
    price: 0.75,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["bread", "soft"],
    variations: [],
    addOns: [],
    nutrition: { calories: "120kcal", protein: "3g", allergens: ["gluten", "dairy", "egg"] },
    preparationTime: 1,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_poutine",
    name: "Poutine",
    description: "French fries with gravy and cheese curds.",
    price: 6.99,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 0,
    tags: ["canadian", "cheese", "popular"],
    variations: [],
    addOns: [],
    nutrition: { calories: "520kcal", protein: "12g", allergens: ["gluten", "dairy"] },
    preparationTime: 5,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_curly_poutine",
    name: "Poutine - Curly Fries",
    description: "Curly fries with gravy and cheese curds.",
    price: 9.99,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["canadian", "cheese", "curly"],
    variations: [],
    addOns: [],
    nutrition: { calories: "580kcal", protein: "13g", allergens: ["gluten", "dairy"] },
    preparationTime: 6,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_tiramisu_cheesecake",
    name: "Tiramisu Cheese Cake",
    description: "Rich tiramisu flavored cheesecake.",
    price: 6.99,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["dessert", "sweet", "premium"],
    variations: [],
    addOns: [],
    nutrition: { calories: "420kcal", protein: "7g", allergens: ["dairy", "gluten", "egg"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_caramel_chocolate_cake",
    name: "Caramel Chocolate Cake",
    description: "Decadent chocolate cake with caramel drizzle.",
    price: 6.99,
    category: "Sides & Dessert",
    categoryId: "cat_sides_dessert",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["dessert", "chocolate", "caramel"],
    variations: [],
    addOns: [],
    nutrition: { calories: "480kcal", protein: "6g", allergens: ["dairy", "gluten", "egg"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Kids Meals
  {
    id: "item_sandwich_kids_meal",
    name: "1 Sandwich Kids Meal",
    description: "Kid-sized sandwich with side and drink.",
    price: 6.99,
    category: "Kids Meals",
    categoryId: "cat_kids_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["kids", "meal", "sandwich"],
    variations: [],
    addOns: [],
    nutrition: { calories: "480kcal", protein: "22g", allergens: ["gluten", "dairy", "soy", "egg"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_strips_kids_meal",
    name: "2 Strips Kids Meal",
    description: "Two chicken strips with side and drink.",
    price: 6.99,
    category: "Kids Meals",
    categoryId: "cat_kids_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 0,
    tags: ["kids", "meal", "strips", "popular"],
    variations: [],
    addOns: [],
    nutrition: { calories: "420kcal", protein: "25g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_nuggets_kids_meal",
    name: "5 Nuggets Kids Meal",
    description: "Five chicken nuggets with side and drink.",
    price: 6.99,
    category: "Kids Meals",
    categoryId: "cat_kids_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["kids", "meal", "nuggets"],
    variations: [],
    addOns: [],
    nutrition: { calories: "400kcal", protein: "24g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "item_drumstick_kids_meal",
    name: "1 Drumstick Kids Meal",
    description: "One chicken drumstick with side and drink.",
    price: 6.99,
    category: "Kids Meals",
    categoryId: "cat_kids_meals",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["kids", "meal", "drumstick"],
    variations: [],
    addOns: [],
    nutrition: { calories: "380kcal", protein: "20g", allergens: ["gluten", "soy"] },
    preparationTime: 8,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Dipping Sauces
  {
    id: "sauce_honey_mustard",
    name: "Honey Mustard",
    description: "Sweet and tangy honey mustard sauce.",
    price: 0.79,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["sauce", "sweet", "tangy"],
    variations: [],
    addOns: [],
    nutrition: { calories: "60kcal", protein: "0g", allergens: ["honey"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "sauce_bbq",
    name: "BBQ",
    description: "Classic smoky BBQ sauce.",
    price: 0.79,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["sauce", "smoky", "classic"],
    variations: [],
    addOns: [],
    nutrition: { calories: "45kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "sauce_thai_chilli",
    name: "Thai Chilli",
    description: "Sweet and spicy Thai chilli sauce.",
    price: 0.79,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 2,
    tags: ["sauce", "spicy", "sweet"],
    variations: [],
    addOns: [],
    nutrition: { calories: "50kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "sauce_plum",
    name: "Plum",
    description: "Sweet plum sauce with Asian flavors.",
    price: 0.79,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["sauce", "sweet", "asian"],
    variations: [],
    addOns: [],
    nutrition: { calories: "55kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "sauce_ranch",
    name: "Ranch",
    description: "Creamy ranch dressing.",
    price: 0.99,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 0,
    tags: ["sauce", "creamy", "popular"],
    variations: [],
    addOns: [],
    nutrition: { calories: "80kcal", protein: "1g", allergens: ["dairy", "egg"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "sauce_buffalo_hot",
    name: "Buffalo Hot",
    description: "Spicy buffalo sauce with kick.",
    price: 0.99,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 3,
    tags: ["sauce", "spicy", "hot"],
    variations: [],
    addOns: [],
    nutrition: { calories: "25kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "sauce_honey_garlic",
    name: "Honey Garlic",
    description: "Sweet honey garlic sauce.",
    price: 0.99,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["sauce", "sweet", "garlic"],
    variations: [],
    addOns: [],
    nutrition: { calories: "65kcal", protein: "0g", allergens: ["honey"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "sauce_butter_chicken",
    name: "Butter Chicken Dip",
    description: "Creamy butter chicken flavored sauce.",
    price: 0.99,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["sauce", "creamy", "butter"],
    variations: [],
    addOns: [],
    nutrition: { calories: "70kcal", protein: "1g", allergens: ["dairy"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "sauce_mayo",
    name: "Regular Mayo",
    description: "Classic mayonnaise.",
    price: 0.99,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["sauce", "classic"],
    variations: [],
    addOns: [],
    nutrition: { calories: "90kcal", protein: "0g", allergens: ["egg"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "sauce_spicy_mayo",
    name: "Mild Spicy Mayo",
    description: "Mayonnaise with a mild spicy kick.",
    price: 0.99,
    category: "Dipping Sauces",
    categoryId: "cat_sauces",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 1,
    tags: ["sauce", "spicy", "mild"],
    variations: [],
    addOns: [],
    nutrition: { calories: "95kcal", protein: "0g", allergens: ["egg"] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },

  // Drinks
  {
    id: "drink_can_pop",
    name: "Can Pop (355ml)",
    description: "Refreshing canned soft drink.",
    price: 1.99,
    category: "Drinks",
    categoryId: "cat_drinks",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["drink", "cold", "can"],
    variations: [],
    addOns: [],
    nutrition: { calories: "140kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "drink_bottle_pop",
    name: "Bottle Pop (591ml)",
    description: "Refreshing bottled soft drink.",
    price: 2.49,
    category: "Drinks",
    categoryId: "cat_drinks",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: true,
    spicyLevel: 0,
    tags: ["drink", "cold", "bottle", "popular"],
    variations: [],
    addOns: [],
    nutrition: { calories: "230kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "drink_pure_leaf",
    name: "Pure Leaf (547ml)",
    description: "Premium iced tea.",
    price: 3.99,
    category: "Drinks",
    categoryId: "cat_drinks",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["drink", "tea", "premium"],
    variations: [],
    addOns: [],
    nutrition: { calories: "120kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "drink_bubly",
    name: "Bubly (355ml)",
    description: "Sparkling water with natural flavors.",
    price: 2.49,
    category: "Drinks",
    categoryId: "cat_drinks",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["drink", "sparkling", "healthy"],
    variations: [],
    addOns: [],
    nutrition: { calories: "0kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "drink_gatorade",
    name: "Gatorade (591ml)",
    description: "Sports drink for hydration.",
    price: 3.99,
    category: "Drinks",
    categoryId: "cat_drinks",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["drink", "sports", "hydration"],
    variations: [],
    addOns: [],
    nutrition: { calories: "140kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "drink_rockstar",
    name: "Rockstar (473ml)",
    description: "Energy drink for boost.",
    price: 3.99,
    category: "Drinks",
    categoryId: "cat_drinks",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["drink", "energy", "boost"],
    variations: [],
    addOns: [],
    nutrition: { calories: "160kcal", protein: "0g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "drink_fresh_juice",
    name: "Fresh Juice Can (340ml)",
    description: "Fresh fruit juice in a can.",
    price: 3.99,
    category: "Drinks",
    categoryId: "cat_drinks",
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    isFeatured: false,
    spicyLevel: 0,
    tags: ["drink", "juice", "fresh"],
    variations: [],
    addOns: [],
    nutrition: { calories: "110kcal", protein: "1g", allergens: [] },
    preparationTime: 0,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
]

const sampleComboMeals = [
  {
    id: "combo_2pc_meal",
    name: "2pc Chicken Combo",
    description: "2 pieces of chicken with fries and drink.",
    price: 12.99,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    items: [
      { itemId: "item_2pc_chicken_only", quantity: 1 },
      { itemId: "item_french_fries", quantity: 1 },
      { itemId: "drink_bottle_pop", quantity: 1 },
    ],
    isFeatured: true,
    tags: ["value", "popular"],
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "combo_family_feast",
    name: "Family Feast Combo",
    description: "12 pieces of chicken with family sides and drinks.",
    price: 54.99,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    items: [
      { itemId: "item_12pc_chicken", quantity: 1 },
      { itemId: "item_french_fries", quantity: 1, selectedVariation: { Size: "Family" } },
      { itemId: "item_coleslaw", quantity: 1, selectedVariation: { Size: "Large" } },
      { itemId: "drink_bottle_pop", quantity: 4 },
    ],
    isFeatured: true,
    tags: ["family", "value"],
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "combo_tender_special",
    name: "Tender Special Combo",
    description: "6 tenders with curly fries and drink.",
    price: 18.99,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: true,
    items: [
      { itemId: "item_6pc_tenders", quantity: 1 },
      { itemId: "item_curly_fries", quantity: 1 },
      { itemId: "drink_bottle_pop", quantity: 1 },
    ],
    isFeatured: false,
    tags: ["tender", "value"],
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "combo_wings_feast",
    name: "Wings Feast Combo",
    description: "20 wings with poutine and 2 drinks.",
    price: 24.99,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    isActive: false, // Inactive combo
    items: [
      { itemId: "item_10pc_wings", quantity: 2 },
      { itemId: "item_poutine", quantity: 1 },
      { itemId: "drink_bottle_pop", quantity: 2 },
    ],
    isFeatured: false,
    tags: ["wings", "sharing"],
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
]

const sampleOffers = [
  {
    id: "offer_family_special",
    title: "Family Feast Deal",
    description: "Get our 12pc Family Meal for just $44.99 - Save $5!",
    code: "FAMILY5",
    discountType: "fixed",
    discountValue: 5,
    applicableCategoryIds: ["cat_family_meals"],
    applicableItemIds: ["item_12pc_family_meal"],
    minimumPurchase: 40,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    link: "/menu",
    discount: "$5 OFF",
    isActive: true,
    startDate: new Date().toISOString(),
    endDate: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "offer_tender_tuesday",
    title: "Tender Tuesday",
    description: "All tenders 20% off every Tuesday!",
    code: "TENDER20",
    discountType: "percentage",
    discountValue: 20,
    applicableCategoryIds: ["cat_tenders"],
    applicableItemIds: [],
    minimumPurchase: 0,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    link: "/menu",
    discount: "20% OFF",
    isActive: true,
    startDate: new Date().toISOString(),
    endDate: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "offer_twister_combo",
    title: "Twister Combo Special",
    description: "Any twister combo for just $10.99!",
    code: "TWISTER10",
    discountType: "fixed",
    discountValue: 2,
    applicableCategoryIds: ["cat_twisters"],
    applicableItemIds: ["item_twister_combo"],
    minimumPurchase: 0,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    link: "/menu",
    discount: "$2 OFF",
    isActive: true,
    startDate: new Date().toISOString(),
    endDate: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(),
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
  {
    id: "offer_wings_weekend",
    title: "Weekend Wings",
    description: "Buy 10 wings, get 5 free every weekend!",
    code: "WINGS15",
    discountType: "percentage",
    discountValue: 33,
    applicableCategoryIds: ["cat_wings_more"],
    applicableItemIds: ["item_10pc_wings"],
    minimumPurchase: 0,
    image: "https://res.cloudinary.com/dokqexnoi/image/upload/v1736053004/818abd7e-0605-4b56-9e97-fe3773335da6.png",
    link: "/menu",
    discount: "33% OFF",
    isActive: false, // Inactive offer
    startDate: new Date().toISOString(),
    endDate: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  },
]

async function seedCollection(collectionName: string, data: any[], clearExisting = false) {
  const collectionRef = collection(db, collectionName)
  const batch = writeBatch(db)

  if (clearExisting) {
    const q = query(collectionRef)
    const snapshot = await getDocs(q)
    snapshot.docs.forEach((doc) => batch.delete(doc.ref))
    toast.info(`Cleared existing documents from ${collectionName}.`)
  }

  data.forEach((item) => {
    const docRef = doc(collectionRef, item.id)
    batch.set(docRef, item)
  })

  await batch.commit()
  toast.success(`Successfully seeded ${data.length} documents into ${collectionName}.`)
}

export default function DeveloperPage() {
  const [isLoading, setIsLoading] = useState(false)
  const [clearData, setClearData] = useState(false)

  const handleSeedAll = async () => {
    setIsLoading(true)
    toast.info("Starting database seed process...")
    try {
      await seedCollection("categories", sampleCategories, clearData)
      await seedCollection("menuItems", sampleMenuItems, clearData)
      await seedCollection("comboMeals", sampleComboMeals, clearData)
      await seedCollection("offers", sampleOffers, clearData)
      toast.success("All collections seeded successfully!")
    } catch (error) {
      console.error("Error seeding database: ", error)
      toast.error("Error seeding database. Check console for details.")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="space-y-8">
      <Card className="bg-black border border-orange-500/20 shadow-lg">
        <CardHeader>
          <CardTitle className="text-2xl font-bold text-orange-400">Developer Tools</CardTitle>
          <CardDescription className="text-gray-400">
            Use these tools to manage and seed your application's database with the complete Alcatraz Chicken menu.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <Alert variant="destructive" className="bg-red-900/30 border-red-700 text-red-300">
            <Terminal className="h-4 w-4 !text-red-300" />
            <AlertTitle>Warning!</AlertTitle>
            <AlertDescription>
              Seeding data will add sample documents. If 'Clear Existing Data' is checked, it will DELETE all existing
              documents in the collections before seeding. This action cannot be undone.
            </AlertDescription>
          </Alert>

          <div className="flex items-center space-x-2">
            <input
              type="checkbox"
              id="clearData"
              checked={clearData}
              onChange={(e) => setClearData(e.target.checked)}
              className="h-4 w-4 rounded border-gray-600 bg-gray-700 text-orange-500 focus:ring-orange-400 accent-orange-500"
            />
            <label htmlFor="clearData" className="text-sm font-medium text-gray-300">
              Clear Existing Data before Seeding
            </label>
          </div>

          <Button
            onClick={handleSeedAll}
            disabled={isLoading}
            className="w-full sm:w-auto bg-orange-600 hover:bg-orange-700 text-white font-semibold"
          >
            {isLoading ? (
              <div className="animate-spin rounded-full h-5 w-5 border-t-2 border-b-2 border-white mr-2"></div>
            ) : null}
            {isLoading ? "Seeding Database..." : "Seed Complete Alcatraz Menu"}
          </Button>

          <div className="text-xs text-gray-500 space-y-1">
            <p>This will seed the complete Alcatraz Chicken menu: </p>
            <ul className="list-disc list-inside pl-4">
              <li>{sampleCategories.length} Categories (Chicken Only, Tenders, Wings, etc.)</li>
              <li>{sampleMenuItems.length} Menu Items (All sizes and variations)</li>
              <li>{sampleComboMeals.length} Combo Meals</li>
              <li>{sampleOffers.length} Special Offers</li>
            </ul>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
